export EDITOR='vim'
# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

export FZF_BASE=$HOME/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-junegunn-SLASH-fzf.git/

source $HOME/conf/zsh/antigen.zsh
source $HOME/conf/zsh/zi.zsh

antigen use oh-my-zsh

antigen bundle autojump
antigen bundle command-not-found
antigen bundle common-aliases
antigen bundle cp
antigen bundle debian
antigen bundle ubuntu
antigen bundle dircycle
antigen bundle dirhistory
antigen bundle docker
antigen bundle docker-compose
antigen bundle encode64
antigen bundle fzf-zsh
antigen bundle git
antigen bundle gitfast
antigen bundle node
antigen bundle npm
antigen bundle nvm
antigen bundle pass
antigen bundle sudo
antigen bundle tmux
antigen bundle yarn
antigen bundle urltools
antigen bundle wd
antigen bundle web-search
antigen bundle kubectl
antigen bundle zsh_reload
antigen bundle httpie
antigen bundle junegunn/fzf
antigen bundle fzf

antigen theme bira

antigen apply

source <(kubectl completion zsh)
alias k=kubectl
complete -F __start_kubectl k

